Data-Base/Assignment 1/실습/StudentManage/student/student/urls.py
from django.urls import path
from myApp import views

urlpatterns = [
    path('', views.display, name='index'),
    path('remove/<int:pk>', views.deleteData, name='index'),
    path('create', views.inputData, name='create'),
    path('edit/<int:pk>', views.updateData, name='update'),
    path('search', views.searchData, name='search')
]

Data-Base/Assignment 1/실습/StudentManage/student/myApp/models.py
from django.db import models

# Create your models here.

class Students(models.Model):
    id = models.IntegerField(primary_key=True)
    firstname = models.CharField(max_length=25)
    secondname = models.CharField(max_length=25)
    age = models.IntegerField()
    major = models.CharField(max_length=50)
    address = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Students'

Data-Base/Assignment 1/실습/StudentManage/student/myApp/forms.py
from django import forms
from .models import Students

class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = "__all__"

Data-Base/Assignment 1/실습/StudentManage/student/myApp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Students
from .forms import StudentsForm
from django.contrib import messages

# Create your views here.

def display(request):
    students = Students.objects.all()
    return render(request, 'myApp/index.html', {"students": students})

def inputData(request):
    if request.method == "POST":
        form = StudentsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        messages.warning(request, '올바르게 입력해주세요.')
    else:
        form = StudentsForm()
    return render(request, "myApp/input.html", {'form': form})

def deleteData(request, pk):
    student = Students.objects.get(pk=pk)
    if request.method == "GET":
        student.delete()
        return redirect('/')
    students = Students.objects.all()
    return render(request, 'myApp/index.html', {"students": students})

def updateData(request, pk):
    form = StudentsForm()
    if request.method == "POST":
        student = Students.objects.get(pk=pk)
        student.firstname = request.POST.get('firstname')
        student.secondname = request.POST.get('secondname')
        student.age = request.POST.get('age')
        student.major = request.POST.get('major')
        student.address = request.POST.get('address')
        student.save()
        return redirect('/')
    else:
        form = StudentsForm()
    return render(request, "myApp/update.html", {'form': form, 'id': pk})

def searchData(request):
    students = None
    if 'q' in request.GET:
        q = request.GET['q']
        if q:
            students = Students.objects.all()
            students = students.filter(pk=q)
            if not students:
                messages.warning(request, 'No records found')
        else:
            messages.warning(request, 'No records found')
    return render(request, 'myApp/search.html', {"students": students})

Data-Base/Assignment 1/실습/StudentManage/student/myApp/templates/myApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Categories Database:</title>
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <style>
        #header {
            background-color: #3365AC;
            height: 50px;
            border-radius: 5px;
            color: white;
            display: flex;
            align-items: center;
            padding-left: 200px;
        }
        #addButtonBox {
            width: 100%;
            padding-top: 50px;
        }
        #searchButtonBox {
            width: 100%;
            padding-top: 25px;
            padding-bottom: 25px;
        }
        #addButton {
            color: white;
            background-color: #47C83E;
            font-size: 13px;
            width: 130px;
            height: 25px;
            text-align: center;
            border-radius: 5px;
            margin-left: 700px;
        }
        #searchButton {
            display: inline-block;
            background-color: #3365AC;
            font-size: 13px;
            color: white;
            width: 120px;
            height: 25px;
            text-align: center;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border: 1px solid #DBDBDB;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #DBDBDB;
            padding: 10px;
        }
        #editButton {
            float: left;
            background-color: #74BEDA;
            font-size: 15px;
            width: 110px;
            height: 30px;
            text-align: center;
            line-height: 30px;
            color: white;
            border-radius: 5px;
            margin-right: 3px;
            text-decoration-line: none;
        }
        #deleteButton {
            float: left;
            background-color: #CA5C54;
            font-size: 15px;
            width: 120px;
            height: 30px;
            color: white;
            border-radius: 5px;
            text-align: center;
            line-height: 30px;
            text-decoration-line: none;
        }
        .tableH {
            font-weight: bold;
        }
    </style>
</head>
<body>
<div id="header">
    Student Management System
</div>
<div>
    <div id="addButtonBox">
        <form action="{% url 'create' %}" method="post">
            {% csrf_token %}
            <input id="addButton" type="submit" value="+ Add New Record">
        </form>

    </div>
    <div id="searchButtonBox">
        <form action="{% url 'search' %}">
            <input id="searchInput" type="number" name="q" placeholder="Search">
            <input id="searchButton" value="Search by name" type="submit">
        </form>
    </div>
</div>
<table>
    <tr>
        <td class="tableH">ID</td>
        <td class="tableH">First name</td>
        <td class="tableH">Second name</td>
        <td class="tableH">Age</td>
        <td class="tableH">Major</td>
        <td class="tableH">Address</td>
        <td class="tableH" style="width: 250px;"></td>
    </tr>
{% for student in students %}
    <tr>
        <td>{{ student.id }}</td>
        <td>{{ student.firstname }}</td>
        <td>{{ student.secondname }}</td>
        <td>{{ student.age }}</td>
        <td>{{ student.major }}</td>
        <td>{{ student.address }}</td>
        <td style="width: 250px;">
            <a href="/edit/{{student.id}}" id="editButton"><i class="fas fa-pen"></i> Edit record</a>
            <a href="/remove/{{student.id}}" id="deleteButton"><i class="fas fa-eraser"></i> Delete record</a>
        </td>
    </tr>
{% endfor %}
</table>
</body>
</html>

Data-Base/Assignment 1/실습/StudentManage/student/myApp/templates/myApp/input.html
<!DOCTYPE html>
<html>
<head>
    <style>
        #header {
            background-color: #3365AC;
            height: 50px;
            border-radius: 5px;
            color: white;
            display: flex;
            align-items: center;
            padding-left: 200px;
        }
        .title {
            font-size: 23px;
            margin-left: 50px;
        }
        label {
            display: inline-block;
            width: 70px;
            text-align: center;
            margin-bottom: 5px;
            padding-bottom: 20px;
        }
        .container {
            margin-top: 40px;
            margin-left: 400px;
        }
        .submitBtn {
            background-color: #3365AC;
            border-radius: 5px;
            width: 70px;
            height: 35px;
            color: white;
            font-size: 15px;
            margin-left: 70px;
        }
    </style>
</head>
<body>
<div id="header">
    Student Management System
</div>
<div class="container">
    <p class="title">Add new record</p>
    <form action="" method="post">
    {% csrf_token %}
        <div>
            <label>ID: </label>{{ form.id }}
        </div>
        <div>
            <label>First name: </label>{{ form.firstname }}
        </div>
        <div>
            <label>Second name: </label>{{ form.secondname }}
        </div>
        <div>
            <label>Age: </label>{{ form.age }}
        </div>
        <div>
            <label>Major: </label>{{ form.major }}
        </div>
        <div>
            <label>Address: </label>{{ form.address }}
        </div>
        <button type="submit" class="submitBtn">Submit</button>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
</body>
</html>

Data-Base/Assignment 1/실습/StudentManage/student/myApp/templates/myApp/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Categories Database:</title>
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <style>
        #header {
            background-color: #3365AC;
            height: 50px;
            border-radius: 5px;
            color: white;
            display: flex;
            align-items: center;
            padding-left: 200px;
        }
        table {
            width: 100%;
            border: 1px solid #DBDBDB;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #DBDBDB;
            padding: 10px;
        }
        .tableH {
            font-weight: bold;
        }
        .title {
            text-align: center;
            font-size: 25px;
            margin-bottom: 50px;
        }
        .context {
            text-align: center;
            font-size: 25px;
            color: red;
        }
    </style>
</head>
<body>
<div id="header">
    Student Management System
</div>
<div>
    <h3 class="title">Search results</h3>
    {% if messages %}
        {% for message in messages %}
        <div class="context">{{ message }}</div>
        {% endfor %}
    {% endif %}
</div>
<table>
    <tr>
        <td class="tableH">ID</td>
        <td class="tableH">First name</td>
        <td class="tableH">Second name</td>
        <td class="tableH">Age</td>
        <td class="tableH">Major</td>
        <td class="tableH">Address</td>
    </tr>
{% for student in students %}
    <tr>
        <td>{{ student.id }}</td>
        <td>{{ student.firstname }}</td>
        <td>{{ student.secondname }}</td>
        <td>{{ student.age }}</td>
        <td>{{ student.major }}</td>
        <td>{{ student.address }}</td>
    </tr>
{% endfor %}
</table>
</body>
</html>

Data-Base/Assignment 1/실습/StudentManage/student/myApp/templates/myApp/update.html
<!DOCTYPE html>
<html>
<head>
    <style>
        #header {
            background-color: #3365AC;
            height: 50px;
            border-radius: 5px;
            color: white;
            display: flex;
            align-items: center;
            padding-left: 200px;
        }
        .title {
            font-size: 23px;
            margin-left: 50px;
        }
        label {
            display: inline-block;
            width: 70px;
            text-align: center;
            margin-bottom: 5px;
            padding-bottom: 20px;
        }
        .container {
            margin-top: 40px;
            margin-left: 400px;
        }
        .submitBtn {
            background-color: #3365AC;
            border-radius: 5px;
            width: 70px;
            height: 35px;
            color: white;
            font-size: 15px;
            margin-left: 70px;
        }
    </style>
</head>
<body>
<div id="header">
    Student Management System
</div>
<div class="container">
    <p class="title">Update record</p>
    <form action="" method="post">
    {% csrf_token %}
        <div>
            <label>ID: </label>
            <input type="number" name="id" value="{{id}}" id="id_id"readonly>
        </div>
        <div>
            <label>First name: </label>{{ form.firstname }}
        </div>
        <div>
            <label>Second name: </label>{{ form.secondname }}
        </div>
        <div>
            <label>Age: </label>{{ form.age }}
        </div>
        <div>
            <label>Major: </label>{{ form.major }}
        </div>
        <div>
            <label>Address: </label>{{ form.address }}
        </div>
        <button type="submit" class="submitBtn">Update</button>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
</body>
</html>